# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build and push Docker Images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: docker.pkg.github.com
        username: diegodejesus
        password: ${{ secrets.ACCESS_TOKEN }}
        repository: diegodejesus/simple-python-api/simple-python-api
        tag_with_sha: true
        
    
    - name: checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: diegodejesus/simple-python-api-charts
        path: simple-python-api-charts
    
    - name: Update Version
      run: |
        cd simpe-python-api-charts/
        sed -i 's|diegodejesus/simple-python-api:.*|diegodejesus/simple-python-api:${DOCKER_TAG}|g' deployment.yaml
        git add .
        git commit -am "Updating version on docker container to ${DOCKER_TAG}"
        git push origin master
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: echo Successfully pushed to repository
